*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /SPROLIMS/VCCODE................................*
FORM GET_DATA_/SPROLIMS/VCCODE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /SPROLIMS/TCCODE WHERE
(VIM_WHERETAB) .
    CLEAR /SPROLIMS/VCCODE .
/SPROLIMS/VCCODE-MANDT =
/SPROLIMS/TCCODE-MANDT .
/SPROLIMS/VCCODE-OTKAT =
/SPROLIMS/TCCODE-OTKAT .
/SPROLIMS/VCCODE-OTGRP =
/SPROLIMS/TCCODE-OTGRP .
/SPROLIMS/VCCODE-DESCR_OTGRP =
/SPROLIMS/TCCODE-DESCR_OTGRP .
<VIM_TOTAL_STRUC> = /SPROLIMS/VCCODE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/SPROLIMS/VCCODE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /SPROLIMS/VCCODE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/SPROLIMS/VCCODE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /SPROLIMS/TCCODE WHERE
  OTKAT = /SPROLIMS/VCCODE-OTKAT AND
  OTGRP = /SPROLIMS/VCCODE-OTGRP .
    IF SY-SUBRC = 0.
    DELETE /SPROLIMS/TCCODE .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /SPROLIMS/TCCODE WHERE
  OTKAT = /SPROLIMS/VCCODE-OTKAT AND
  OTGRP = /SPROLIMS/VCCODE-OTGRP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /SPROLIMS/TCCODE.
    ENDIF.
/SPROLIMS/TCCODE-MANDT =
/SPROLIMS/VCCODE-MANDT .
/SPROLIMS/TCCODE-OTKAT =
/SPROLIMS/VCCODE-OTKAT .
/SPROLIMS/TCCODE-OTGRP =
/SPROLIMS/VCCODE-OTGRP .
/SPROLIMS/TCCODE-DESCR_OTGRP =
/SPROLIMS/VCCODE-DESCR_OTGRP .
    IF SY-SUBRC = 0.
    UPDATE /SPROLIMS/TCCODE ##WARN_OK.
    ELSE.
    INSERT /SPROLIMS/TCCODE .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/SPROLIMS/VCCODE-UPD_FLAG,
STATUS_/SPROLIMS/VCCODE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/SPROLIMS/VCCODE.
  SELECT SINGLE * FROM /SPROLIMS/TCCODE WHERE
OTKAT = /SPROLIMS/VCCODE-OTKAT AND
OTGRP = /SPROLIMS/VCCODE-OTGRP .
/SPROLIMS/VCCODE-MANDT =
/SPROLIMS/TCCODE-MANDT .
/SPROLIMS/VCCODE-OTKAT =
/SPROLIMS/TCCODE-OTKAT .
/SPROLIMS/VCCODE-OTGRP =
/SPROLIMS/TCCODE-OTGRP .
/SPROLIMS/VCCODE-DESCR_OTGRP =
/SPROLIMS/TCCODE-DESCR_OTGRP .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/SPROLIMS/VCCODE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /SPROLIMS/VCCODE-OTKAT TO
/SPROLIMS/TCCODE-OTKAT .
MOVE /SPROLIMS/VCCODE-OTGRP TO
/SPROLIMS/TCCODE-OTGRP .
MOVE /SPROLIMS/VCCODE-MANDT TO
/SPROLIMS/TCCODE-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/SPROLIMS/TCCODE'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /SPROLIMS/TCCODE TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/SPROLIMS/TCCODE'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
