*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /SPROLIMS/V_USER................................*
FORM GET_DATA_/SPROLIMS/V_USER.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /SPROLIMS/T_USER WHERE
(VIM_WHERETAB) .
    CLEAR /SPROLIMS/V_USER .
/SPROLIMS/V_USER-MANDT =
/SPROLIMS/T_USER-MANDT .
/SPROLIMS/V_USER-WERKS =
/SPROLIMS/T_USER-WERKS .
/SPROLIMS/V_USER-MAILBTP =
/SPROLIMS/T_USER-MAILBTP .
/SPROLIMS/V_USER-UNAME =
/SPROLIMS/T_USER-UNAME .
/SPROLIMS/V_USER-APPLICATION =
/SPROLIMS/T_USER-APPLICATION .
<VIM_TOTAL_STRUC> = /SPROLIMS/V_USER.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/SPROLIMS/V_USER .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /SPROLIMS/V_USER.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/SPROLIMS/V_USER-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /SPROLIMS/T_USER WHERE
  WERKS = /SPROLIMS/V_USER-WERKS AND
  MAILBTP = /SPROLIMS/V_USER-MAILBTP AND
  UNAME = /SPROLIMS/V_USER-UNAME AND
  APPLICATION = /SPROLIMS/V_USER-APPLICATION .
    IF SY-SUBRC = 0.
    DELETE /SPROLIMS/T_USER .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /SPROLIMS/T_USER WHERE
  WERKS = /SPROLIMS/V_USER-WERKS AND
  MAILBTP = /SPROLIMS/V_USER-MAILBTP AND
  UNAME = /SPROLIMS/V_USER-UNAME AND
  APPLICATION = /SPROLIMS/V_USER-APPLICATION .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /SPROLIMS/T_USER.
    ENDIF.
/SPROLIMS/T_USER-MANDT =
/SPROLIMS/V_USER-MANDT .
/SPROLIMS/T_USER-WERKS =
/SPROLIMS/V_USER-WERKS .
/SPROLIMS/T_USER-MAILBTP =
/SPROLIMS/V_USER-MAILBTP .
/SPROLIMS/T_USER-UNAME =
/SPROLIMS/V_USER-UNAME .
/SPROLIMS/T_USER-APPLICATION =
/SPROLIMS/V_USER-APPLICATION .
    IF SY-SUBRC = 0.
    UPDATE /SPROLIMS/T_USER ##WARN_OK.
    ELSE.
    INSERT /SPROLIMS/T_USER .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/SPROLIMS/V_USER-UPD_FLAG,
STATUS_/SPROLIMS/V_USER-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/SPROLIMS/V_USER.
  SELECT SINGLE * FROM /SPROLIMS/T_USER WHERE
WERKS = /SPROLIMS/V_USER-WERKS AND
MAILBTP = /SPROLIMS/V_USER-MAILBTP AND
UNAME = /SPROLIMS/V_USER-UNAME AND
APPLICATION = /SPROLIMS/V_USER-APPLICATION .
/SPROLIMS/V_USER-MANDT =
/SPROLIMS/T_USER-MANDT .
/SPROLIMS/V_USER-WERKS =
/SPROLIMS/T_USER-WERKS .
/SPROLIMS/V_USER-MAILBTP =
/SPROLIMS/T_USER-MAILBTP .
/SPROLIMS/V_USER-UNAME =
/SPROLIMS/T_USER-UNAME .
/SPROLIMS/V_USER-APPLICATION =
/SPROLIMS/T_USER-APPLICATION .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/SPROLIMS/V_USER USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /SPROLIMS/V_USER-WERKS TO
/SPROLIMS/T_USER-WERKS .
MOVE /SPROLIMS/V_USER-MAILBTP TO
/SPROLIMS/T_USER-MAILBTP .
MOVE /SPROLIMS/V_USER-UNAME TO
/SPROLIMS/T_USER-UNAME .
MOVE /SPROLIMS/V_USER-APPLICATION TO
/SPROLIMS/T_USER-APPLICATION .
MOVE /SPROLIMS/V_USER-MANDT TO
/SPROLIMS/T_USER-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/SPROLIMS/T_USER'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /SPROLIMS/T_USER TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/SPROLIMS/T_USER'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
