*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /SPROLIMS/VCCODP................................*
FORM GET_DATA_/SPROLIMS/VCCODP.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /SPROLIMS/TCCODP WHERE
(VIM_WHERETAB) .
    CLEAR /SPROLIMS/VCCODP .
/SPROLIMS/VCCODP-MANDT =
/SPROLIMS/TCCODP-MANDT .
/SPROLIMS/VCCODP-OTKAT =
/SPROLIMS/TCCODP-OTKAT .
/SPROLIMS/VCCODP-OTGRP =
/SPROLIMS/TCCODP-OTGRP .
/SPROLIMS/VCCODP-OTEIL =
/SPROLIMS/TCCODP-OTEIL .
/SPROLIMS/VCCODP-DESCR_OTEIL =
/SPROLIMS/TCCODP-DESCR_OTEIL .
/SPROLIMS/VCCODP-DESCR_COMP_OTEIL =
/SPROLIMS/TCCODP-DESCR_COMP_OTEIL .
    SELECT SINGLE * FROM /SPROLIMS/TCCODE WHERE
OTKAT = /SPROLIMS/TCCODP-OTKAT AND
OTGRP = /SPROLIMS/TCCODP-OTGRP .
    IF SY-SUBRC EQ 0.
    ENDIF.
<VIM_TOTAL_STRUC> = /SPROLIMS/VCCODP.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/SPROLIMS/VCCODP .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /SPROLIMS/VCCODP.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/SPROLIMS/VCCODP-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /SPROLIMS/TCCODP WHERE
  OTKAT = /SPROLIMS/VCCODP-OTKAT AND
  OTGRP = /SPROLIMS/VCCODP-OTGRP AND
  OTEIL = /SPROLIMS/VCCODP-OTEIL .
    IF SY-SUBRC = 0.
    DELETE /SPROLIMS/TCCODP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /SPROLIMS/TCCODP WHERE
  OTKAT = /SPROLIMS/VCCODP-OTKAT AND
  OTGRP = /SPROLIMS/VCCODP-OTGRP AND
  OTEIL = /SPROLIMS/VCCODP-OTEIL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /SPROLIMS/TCCODP.
    ENDIF.
/SPROLIMS/TCCODP-MANDT =
/SPROLIMS/VCCODP-MANDT .
/SPROLIMS/TCCODP-OTKAT =
/SPROLIMS/VCCODP-OTKAT .
/SPROLIMS/TCCODP-OTGRP =
/SPROLIMS/VCCODP-OTGRP .
/SPROLIMS/TCCODP-OTEIL =
/SPROLIMS/VCCODP-OTEIL .
/SPROLIMS/TCCODP-DESCR_OTEIL =
/SPROLIMS/VCCODP-DESCR_OTEIL .
/SPROLIMS/TCCODP-DESCR_COMP_OTEIL =
/SPROLIMS/VCCODP-DESCR_COMP_OTEIL .
    IF SY-SUBRC = 0.
    UPDATE /SPROLIMS/TCCODP ##WARN_OK.
    ELSE.
    INSERT /SPROLIMS/TCCODP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/SPROLIMS/VCCODP-UPD_FLAG,
STATUS_/SPROLIMS/VCCODP-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/SPROLIMS/VCCODP.
  SELECT SINGLE * FROM /SPROLIMS/TCCODP WHERE
OTKAT = /SPROLIMS/VCCODP-OTKAT AND
OTGRP = /SPROLIMS/VCCODP-OTGRP AND
OTEIL = /SPROLIMS/VCCODP-OTEIL .
/SPROLIMS/VCCODP-MANDT =
/SPROLIMS/TCCODP-MANDT .
/SPROLIMS/VCCODP-OTKAT =
/SPROLIMS/TCCODP-OTKAT .
/SPROLIMS/VCCODP-OTGRP =
/SPROLIMS/TCCODP-OTGRP .
/SPROLIMS/VCCODP-OTEIL =
/SPROLIMS/TCCODP-OTEIL .
/SPROLIMS/VCCODP-DESCR_OTEIL =
/SPROLIMS/TCCODP-DESCR_OTEIL .
/SPROLIMS/VCCODP-DESCR_COMP_OTEIL =
/SPROLIMS/TCCODP-DESCR_COMP_OTEIL .
    SELECT SINGLE * FROM /SPROLIMS/TCCODE WHERE
OTKAT = /SPROLIMS/TCCODP-OTKAT AND
OTGRP = /SPROLIMS/TCCODP-OTGRP .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/SPROLIMS/VCCODP USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /SPROLIMS/VCCODP-OTKAT TO
/SPROLIMS/TCCODP-OTKAT .
MOVE /SPROLIMS/VCCODP-OTGRP TO
/SPROLIMS/TCCODP-OTGRP .
MOVE /SPROLIMS/VCCODP-OTEIL TO
/SPROLIMS/TCCODP-OTEIL .
MOVE /SPROLIMS/VCCODP-MANDT TO
/SPROLIMS/TCCODP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/SPROLIMS/TCCODP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /SPROLIMS/TCCODP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/SPROLIMS/TCCODP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/SPROLIMS/VCCODP USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/SPROLIMS/TCCODP-MANDT =
/SPROLIMS/VCCODP-MANDT .
/SPROLIMS/TCCODP-OTKAT =
/SPROLIMS/VCCODP-OTKAT .
/SPROLIMS/TCCODP-OTGRP =
/SPROLIMS/VCCODP-OTGRP .
/SPROLIMS/TCCODP-OTEIL =
/SPROLIMS/VCCODP-OTEIL .
/SPROLIMS/TCCODP-DESCR_OTEIL =
/SPROLIMS/VCCODP-DESCR_OTEIL .
/SPROLIMS/TCCODP-DESCR_COMP_OTEIL =
/SPROLIMS/VCCODP-DESCR_COMP_OTEIL .
    SELECT SINGLE * FROM /SPROLIMS/TCCODE WHERE
OTKAT = /SPROLIMS/TCCODP-OTKAT AND
OTGRP = /SPROLIMS/TCCODP-OTGRP .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
