*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /SPROLIMS/VDILUI................................*
FORM GET_DATA_/SPROLIMS/VDILUI.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /SPROLIMS/DILUIC WHERE
(VIM_WHERETAB) .
    CLEAR /SPROLIMS/VDILUI .
/SPROLIMS/VDILUI-MANDT =
/SPROLIMS/DILUIC-MANDT .
/SPROLIMS/VDILUI-MATNR =
/SPROLIMS/DILUIC-MATNR .
/SPROLIMS/VDILUI-ANALISE =
/SPROLIMS/DILUIC-ANALISE .
/SPROLIMS/VDILUI-DILUICAO =
/SPROLIMS/DILUIC-DILUICAO .
<VIM_TOTAL_STRUC> = /SPROLIMS/VDILUI.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/SPROLIMS/VDILUI .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /SPROLIMS/VDILUI.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/SPROLIMS/VDILUI-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /SPROLIMS/DILUIC WHERE
  MATNR = /SPROLIMS/VDILUI-MATNR AND
  ANALISE = /SPROLIMS/VDILUI-ANALISE .
    IF SY-SUBRC = 0.
    DELETE /SPROLIMS/DILUIC .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /SPROLIMS/DILUIC WHERE
  MATNR = /SPROLIMS/VDILUI-MATNR AND
  ANALISE = /SPROLIMS/VDILUI-ANALISE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /SPROLIMS/DILUIC.
    ENDIF.
/SPROLIMS/DILUIC-MANDT =
/SPROLIMS/VDILUI-MANDT .
/SPROLIMS/DILUIC-MATNR =
/SPROLIMS/VDILUI-MATNR .
/SPROLIMS/DILUIC-ANALISE =
/SPROLIMS/VDILUI-ANALISE .
/SPROLIMS/DILUIC-DILUICAO =
/SPROLIMS/VDILUI-DILUICAO .
    IF SY-SUBRC = 0.
    UPDATE /SPROLIMS/DILUIC ##WARN_OK.
    ELSE.
    INSERT /SPROLIMS/DILUIC .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/SPROLIMS/VDILUI-UPD_FLAG,
STATUS_/SPROLIMS/VDILUI-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/SPROLIMS/VDILUI.
  SELECT SINGLE * FROM /SPROLIMS/DILUIC WHERE
MATNR = /SPROLIMS/VDILUI-MATNR AND
ANALISE = /SPROLIMS/VDILUI-ANALISE .
/SPROLIMS/VDILUI-MANDT =
/SPROLIMS/DILUIC-MANDT .
/SPROLIMS/VDILUI-MATNR =
/SPROLIMS/DILUIC-MATNR .
/SPROLIMS/VDILUI-ANALISE =
/SPROLIMS/DILUIC-ANALISE .
/SPROLIMS/VDILUI-DILUICAO =
/SPROLIMS/DILUIC-DILUICAO .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/SPROLIMS/VDILUI USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /SPROLIMS/VDILUI-MATNR TO
/SPROLIMS/DILUIC-MATNR .
MOVE /SPROLIMS/VDILUI-ANALISE TO
/SPROLIMS/DILUIC-ANALISE .
MOVE /SPROLIMS/VDILUI-MANDT TO
/SPROLIMS/DILUIC-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/SPROLIMS/DILUIC'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /SPROLIMS/DILUIC TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/SPROLIMS/DILUIC'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
