*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /SPROLIMS/VCCARA................................*
FORM GET_DATA_/SPROLIMS/VCCARA.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /SPROLIMS/TCCARA WHERE
(VIM_WHERETAB) .
    CLEAR /SPROLIMS/VCCARA .
/SPROLIMS/VCCARA-MANDT =
/SPROLIMS/TCCARA-MANDT .
/SPROLIMS/VCCARA-OTKAT =
/SPROLIMS/TCCARA-OTKAT .
/SPROLIMS/VCCARA-WERKS =
/SPROLIMS/TCCARA-WERKS .
/SPROLIMS/VCCARA-CLASS =
/SPROLIMS/TCCARA-CLASS .
/SPROLIMS/VCCARA-CARAC =
/SPROLIMS/TCCARA-CARAC .
<VIM_TOTAL_STRUC> = /SPROLIMS/VCCARA.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/SPROLIMS/VCCARA .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /SPROLIMS/VCCARA.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/SPROLIMS/VCCARA-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /SPROLIMS/TCCARA WHERE
  OTKAT = /SPROLIMS/VCCARA-OTKAT AND
  WERKS = /SPROLIMS/VCCARA-WERKS AND
  CLASS = /SPROLIMS/VCCARA-CLASS .
    IF SY-SUBRC = 0.
    DELETE /SPROLIMS/TCCARA .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /SPROLIMS/TCCARA WHERE
  OTKAT = /SPROLIMS/VCCARA-OTKAT AND
  WERKS = /SPROLIMS/VCCARA-WERKS AND
  CLASS = /SPROLIMS/VCCARA-CLASS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /SPROLIMS/TCCARA.
    ENDIF.
/SPROLIMS/TCCARA-MANDT =
/SPROLIMS/VCCARA-MANDT .
/SPROLIMS/TCCARA-OTKAT =
/SPROLIMS/VCCARA-OTKAT .
/SPROLIMS/TCCARA-WERKS =
/SPROLIMS/VCCARA-WERKS .
/SPROLIMS/TCCARA-CLASS =
/SPROLIMS/VCCARA-CLASS .
/SPROLIMS/TCCARA-CARAC =
/SPROLIMS/VCCARA-CARAC .
    IF SY-SUBRC = 0.
    UPDATE /SPROLIMS/TCCARA ##WARN_OK.
    ELSE.
    INSERT /SPROLIMS/TCCARA .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/SPROLIMS/VCCARA-UPD_FLAG,
STATUS_/SPROLIMS/VCCARA-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/SPROLIMS/VCCARA.
  SELECT SINGLE * FROM /SPROLIMS/TCCARA WHERE
OTKAT = /SPROLIMS/VCCARA-OTKAT AND
WERKS = /SPROLIMS/VCCARA-WERKS AND
CLASS = /SPROLIMS/VCCARA-CLASS .
/SPROLIMS/VCCARA-MANDT =
/SPROLIMS/TCCARA-MANDT .
/SPROLIMS/VCCARA-OTKAT =
/SPROLIMS/TCCARA-OTKAT .
/SPROLIMS/VCCARA-WERKS =
/SPROLIMS/TCCARA-WERKS .
/SPROLIMS/VCCARA-CLASS =
/SPROLIMS/TCCARA-CLASS .
/SPROLIMS/VCCARA-CARAC =
/SPROLIMS/TCCARA-CARAC .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/SPROLIMS/VCCARA USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /SPROLIMS/VCCARA-OTKAT TO
/SPROLIMS/TCCARA-OTKAT .
MOVE /SPROLIMS/VCCARA-WERKS TO
/SPROLIMS/TCCARA-WERKS .
MOVE /SPROLIMS/VCCARA-CLASS TO
/SPROLIMS/TCCARA-CLASS .
MOVE /SPROLIMS/VCCARA-MANDT TO
/SPROLIMS/TCCARA-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/SPROLIMS/TCCARA'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /SPROLIMS/TCCARA TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/SPROLIMS/TCCARA'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
